// voice_list.js

window.VOICE_LIST = {
  'PIANO': [
    { msb: 0, lsb: 115, program: 1, name: "Live! Concert Grand Piano" },
    { msb: 0, lsb: 112, program: 1, name: "Grand Piano" },
    { msb: 0, lsb: 112, program: 2, name: "Bright Piano" },
    { msb: 0, lsb: 112, program: 7, name: "Harpsichord" },
    { msb: 0, lsb: 112, program: 4, name: "Honky Tonk Piano" },
    { msb: 0, lsb: 112, program: 3, name: "MIDI Grand Piano" },
    { msb: 0, lsb: 113, program: 3, name: "CP80" },
  ],
  'E.PIANO': [
    { msb: 0, lsb: 118, program: 5, name: "Cool! SuitcaseEP" },
    { msb: 0, lsb: 118, program: 6, name: "JazzChorusEP" },
    { msb: 0, lsb: 120, program: 5, name: "PhaseEP" },
    { msb: 0, lsb: 119, program: 5, name: "Cool! TremoloEP" },
    { msb: 0, lsb: 121, program: 5, name: "Cool! ElectricPiano" },
    { msb: 0, lsb: 117, program: 5, name: "StageEP" },
    { msb: 0, lsb: 114, program: 5, name: "Cool! Galaxy Electric Piano" },
    { msb: 0, lsb: 113, program: 6, name: "Hyper Tines" },
    { msb: 0, lsb: 112, program: 5, name: "Funky Electric Piano" },
    { msb: 0, lsb: 112, program: 6, name: "DX Modern Electric Piano" },
    { msb: 0, lsb: 114, program: 6, name: "Venus Electric Piano" },
    { msb: 0, lsb: 112, program: 8, name: "Clavi" },
    { msb: 0, lsb: 113, program: 8, name: "WahClavi" },
  ],
  'ORGAN': [
    { msb: 0, lsb: 118, program: 19, name: "Cool! Organ" },
    { msb: 0, lsb: 117, program: 19, name: "Cool! Rotor Organ" },
    { msb: 0, lsb: 112, program: 17, name: "Jazz Organ 1" },
    { msb: 104, lsb: 49, program: 17, name: "Jazz Organ 1 plus RotaryFast" },
    { msb: 0, lsb: 113, program: 17, name: "Jazz Organ 2" },
    { msb: 104, lsb: 50, program: 17, name: "Jazz Organ 2 plus RotaryFast" },
    { msb: 0, lsb: 112, program: 19, name: "Rock Organ" },
    { msb: 0, lsb: 120, program: 19, name: "Octave Shift Organ" },
    { msb: 0, lsb: 114, program: 19, name: "Purple Organ" },
    { msb: 0, lsb: 112, program: 18, name: "Click Organ" },
    { msb: 0, lsb: 116, program: 17, name: "Bright Organ" },
    { msb: 0, lsb: 127, program: 19, name: "Theater Organ" },
    { msb: 0, lsb: 121, program: 20, name: "16' plus 2' Organ" },
    { msb: 0, lsb: 120, program: 20, name: "16' plus 4' Organ" },
    { msb: 0, lsb: 113, program: 20, name: "Chapel Organ" },
    { msb: 0, lsb: 112, program: 20, name: "Pipe Organ" },
    { msb: 0, lsb: 112, program: 21, name: "Reed Organ" },
  ],
  'ACCORDION': [
    { msb: 0, lsb: 112, program: 22, name: "Musette Accordion" },
    { msb: 0, lsb: 113, program: 22, name: "Traditional Accordion" },
    { msb: 0, lsb: 113, program: 24, name: "Bandoneon" },
    { msb: 0, lsb: 113, program: 23, name: "Modern Harp" },
    { msb: 0, lsb: 114, program: 23, name: "Blues Harp" },
    { msb: 0, lsb: 115, program: 23, name: "Harmonica" },
  ],
  'GUITAR': [
    { msb: 8, lsb: 96, program: 1, name: "S.Art Lite " },
    { msb: 8, lsb: 96, program: 2, name: "S.Art Lite " },
    { msb: 8, lsb: 97, program: 1, name: "S.Art Lite " },
    { msb: 8, lsb: 97, program: 2, name: "S.Art Lite Steel Guitar Slide ***" },
    { msb: 8, lsb: 96, program: 6, name: "S.Art Lite Distortion Guitar ***" },
    { msb: 0, lsb: 116, program: 25, name: "Dynamic Nylon Guitar" },
    { msb: 0, lsb: 118, program: 30, name: "Dynamic Overdriven" },
    { msb: 0, lsb: 121, program: 31, name: "Dynamic Distortion Guitar" },
    { msb: 0, lsb: 122, program: 25, name: "Nylon Guitar" },
    { msb: 0, lsb: 112, program: 25, name: "Classical Guitar" },
    { msb: 104, lsb: 25, program: 26, name: "Steel Guitar" },
    { msb: 0, lsb: 112, program: 26, name: "Folk Guitar" },
    { msb: 0, lsb: 112, program: 27, name: "Jazz Guitar" },
    { msb: 0, lsb: 117, program: 28, name: "60s Clean Guitar" },
    { msb: 0, lsb: 113, program: 26, name: "12Strings Guitar" },
    { msb: 0, lsb: 112, program: 28, name: "Clean Guitar" },
    { msb: 0, lsb: 127, program: 28, name: "Wah Guitar" },
    { msb: 0, lsb: 113, program: 27, name: "Octave Guitar" },
    { msb: 0, lsb: 112, program: 29, name: "Muted Guitar" },
    { msb: 0, lsb: 112, program: 30, name: "Overdriven Guitar" },
    { msb: 0, lsb: 112, program: 31, name: "Distortion Guitar" },
    { msb: 0, lsb: 127, program: 31, name: "Wah Distortion Guitar" },
  ],
  'BASS': [
    { msb: 8, lsb: 96, program: 18, name: "S.Art Lite Slap Bass ***" },
    { msb: 0, lsb: 116, program: 34, name: "Dynamic Electric Bass" },
    { msb: 0, lsb: 112, program: 34, name: "Finger Bass" },
    { msb: 0, lsb: 112, program: 33, name: "Acoustic Bass" },
    { msb: 0, lsb: 112, program: 35, name: "Pick Bass" },
    { msb: 0, lsb: 112, program: 36, name: "Fretless Bass" },
    { msb: 0, lsb: 112, program: 37, name: "Slap Bass" },
    { msb: 0, lsb: 121, program: 40, name: "Funk Bass" },
    { msb: 0, lsb: 112, program: 39, name: "Synth Bass" },
    { msb: 0, lsb: 113, program: 39, name: "Hi-Q Bass" },
    { msb: 0, lsb: 113, program: 40, name: "Dance Bass" },
  ],
  'STRINGS': [
    { msb: 8, lsb: 96, program: 50, name: "S.Art Lite Strings ***" },
    { msb: 0, lsb: 117, program: 50, name: "Live! Strings" },
    { msb: 104, lsb: 23, program: 49, name: "Studio Strings" },
    { msb: 0, lsb: 112, program: 49, name: "Strings" },
    { msb: 0, lsb: 112, program: 50, name: "Chamber Strings" },
    { msb: 0, lsb: 115, program: 50, name: "Marcato Strings" },
    { msb: 0, lsb: 113, program: 50, name: "Slow Strings" },
    { msb: 0, lsb: 112, program: 45, name: "Tremolo Strings" },
    { msb: 0, lsb: 112, program: 51, name: "Synth Strings" },
    { msb: 0, lsb: 112, program: 46, name: "Pizzicato Strings" },
    { msb: 0, lsb: 116, program: 46, name: "Orchestra Pizzicato Strings" },
    { msb: 0, lsb: 113, program: 41, name: "Sweet! Violin" },
    { msb: 0, lsb: 112, program: 41, name: "Violin" },
    { msb: 0, lsb: 112, program: 43, name: "Cello" },
    { msb: 0, lsb: 112, program: 44, name: "Contrabass" },
    { msb: 0, lsb: 112, program: 47, name: "Harp" },
    { msb: 0, lsb: 112, program: 56, name: "Orchestra Hit" },
  ],
  'CHOIR': [
    { msb: 8, lsb: 96, program: 55, name: "S.Art Lite Gospel Choir ***" },
    { msb: 0, lsb: 112, program: 53, name: "Choir" },
    { msb: 104, lsb: 12, program: 54, name: "Gospel Hmm" },
    { msb: 104, lsb: 13, program: 54, name: "Gospel Wow" },
    { msb: 0, lsb: 113, program: 53, name: "Vocal Ensemble" },
    { msb: 0, lsb: 112, program: 55, name: "Air Choir" },
    { msb: 0, lsb: 112, program: 54, name: "Vox Humana" },
  ],
  'SAXOPHONE': [
    { msb: 8, lsb: 96, program: 83, name: "S.Art Lite Tenor Sax ***" },
    { msb: 0, lsb: 122, program: 67, name: "Sax Section" },
    { msb: 0, lsb: 117, program: 67, name: "Sweet! Tenor Sax" },
    { msb: 0, lsb: 112, program: 67, name: "Tenor Sax" },
    { msb: 0, lsb: 112, program: 66, name: "Alto Sax" },
    { msb: 0, lsb: 112, program: 65, name: "Soprano Sax" },
    { msb: 0, lsb: 112, program: 68, name: "Baritone Sax" },
    { msb: 0, lsb: 114, program: 67, name: "Breathy Tenor Sax" },
    { msb: 0, lsb: 116, program: 66, name: "Small Sax Section" },
    { msb: 0, lsb: 112, program: 72, name: "Clarinet" },
    { msb: 0, lsb: 112, program: 69, name: "Oboe" },
    { msb: 0, lsb: 112, program: 70, name: "English Horn" },
    { msb: 0, lsb: 112, program: 71, name: "Bassoon" },
  ],
  'TRUMPET': [
    { msb: 0, lsb: 112, program: 57, name: "Trumpet" },
    { msb: 0, lsb: 127, program: 57, name: "Distortion Trumpet" },
    { msb: 0, lsb: 112, program: 58, name: "Trombone" },
    { msb: 0, lsb: 113, program: 58, name: "Trombone Section" },
    { msb: 0, lsb: 112, program: 60, name: "Muted Trumpet" },
    { msb: 0, lsb: 112, program: 61, name: "French Horn" },
    { msb: 0, lsb: 112, program: 59, name: "Tuba" },
  ],
  'BRASS': [
    { msb: 8, lsb: 96, program: 57, name: "S.Art Lite Brass Section ***" },
    { msb: 0, lsb: 117, program: 63, name: "Live! Brass" },
    { msb: 0, lsb: 112, program: 62, name: "Brass Section" },
    { msb: 0, lsb: 113, program: 62, name: "Big Band Brass" },
    { msb: 0, lsb: 116, program: 62, name: "Octave Brass" },
    { msb: 0, lsb: 113, program: 63, name: "80s Brass" },
    { msb: 0, lsb: 119, program: 62, name: "Mellow Horns" },
    { msb: 0, lsb: 115, program: 63, name: "Funky Brass" },
    { msb: 0, lsb: 114, program: 63, name: "Techno Brass" },
    { msb: 0, lsb: 112, program: 63, name: "Synth Brass" },
  ],
  'FLUTE': [
    { msb: 8, lsb: 96, program: 74, name: "S.Art Lite Flute ***" },
    { msb: 0, lsb: 114, program: 74, name: "Sweet! Flute" },
    { msb: 0, lsb: 115, program: 74, name: "Sweet! Classical Flute" },
    { msb: 0, lsb: 112, program: 74, name: "Flute" },
    { msb: 0, lsb: 112, program: 73, name: "Piccolo" },
    { msb: 0, lsb: 112, program: 76, name: "Pan Flute" },
    { msb: 0, lsb: 112, program: 75, name: "Recorder" },
    { msb: 0, lsb: 112, program: 80, name: "Ocarina" },
  ],
  'SYNTH': [
    { msb: 104, lsb: 20, program: 91, name: "Gemini" },
    { msb: 104, lsb: 21, program: 91, name: "Hands Up!" },
    { msb: 0, lsb: 112, program: 81, name: "Square Lead" },
    { msb: 0, lsb: 112, program: 82, name: "Sawtooth Lead" },
    { msb: 0, lsb: 108, program: 82, name: "RS Tech Saw" },
    { msb: 0, lsb: 112, program: 88, name: "Under Heim" },
    { msb: 0, lsb: 112, program: 85, name: "Portatone" },
    { msb: 0, lsb: 115, program: 82, name: "Analogon 1" },
    { msb: 0, lsb: 119, program: 82, name: "Fargo 1" },
    { msb: 104, lsb: 53, program: 82, name: "Analogon 2" },
    { msb: 104, lsb: 54, program: 82, name: "Fargo 2" },
    { msb: 0, lsb: 112, program: 86, name: "Voice Lead" },
    { msb: 0, lsb: 121, program: 82, name: "Funky Lead" },
    { msb: 0, lsb: 118, program: 89, name: "Sweet Heaven" },
    { msb: 0, lsb: 121, program: 89, name: "Dream Heaven" },
    { msb: 0, lsb: 113, program: 89, name: "Symbiont" },
    { msb: 0, lsb: 112, program: 99, name: "Stardust" },
    { msb: 0, lsb: 112, program: 101, name: "Brightness" },
    { msb: 0, lsb: 112, program: 92, name: "Xenon Pad" },
    { msb: 0, lsb: 112, program: 95, name: "Equinox" },
    { msb: 0, lsb: 112, program: 89, name: "Fantasia" },
    { msb: 0, lsb: 113, program: 90, name: "Dark Moon" },
    { msb: 0, lsb: 113, program: 101, name: "Bell Pad" },
    { msb: 0, lsb: 126, program: 90, name: "RS Analog Pad" },
    { msb: 0, lsb: 116, program: 91, name: "RS Short Resonance" },
  ],
  'PERCUSSION': [
    { msb: 0, lsb: 112, program: 12, name: "Vibraphone" },
    { msb: 0, lsb: 113, program: 12, name: "Jazz Vibes" },
    { msb: 0, lsb: 112, program: 13, name: "Marimba" },
    { msb: 0, lsb: 112, program: 14, name: "Xylophone" },
    { msb: 0, lsb: 112, program: 115, name: "Steel Drums" },
    { msb: 0, lsb: 112, program: 9, name: "Celesta" },
    { msb: 0, lsb: 112, program: 11, name: "Music Box" },
    { msb: 0, lsb: 112, program: 15, name: "Tubular Bells" },
    { msb: 0, lsb: 112, program: 48, name: "Timpani" },
  ],
  'WORLD': [
    { msb: 0, lsb: 112, program: 106, name: "Banjo" },
    { msb: 0, lsb: 0, program: 111, name: "Fiddle" },
    { msb: 0, lsb: 0, program: 110, name: "Bagpipe" },
    { msb: 0, lsb: 0, program: 16, name: "Dulcimer 1" },
    { msb: 0, lsb: 35, program: 16, name: "Dulcimer 2" },
    { msb: 0, lsb: 96, program: 16, name: "Cimbalom" },
    { msb: 0, lsb: 121, program: 16, name: "Santur" },
    { msb: 0, lsb: 97, program: 108, name: "Kanoon" },
    { msb: 0, lsb: 98, program: 106, name: "Oud" },
    { msb: 0, lsb: 96, program: 106, name: "Rabab" },
    { msb: 0, lsb: 0, program: 109, name: "Kalimba" },
    { msb: 0, lsb: 113, program: 21, name: "Harmonium 1 (Single Reed)" },
    { msb: 0, lsb: 114, program: 21, name: "Harmonium 2 (Double Reed)" },
    { msb: 0, lsb: 115, program: 21, name: "Harmonium 3 (Triple Reed)" },
    { msb: 0, lsb: 114, program: 105, name: "Tanpura" },
    { msb: 0, lsb: 96, program: 112, name: "Pungi" },
    { msb: 0, lsb: 117, program: 74, name: "Bansuri" },
    { msb: 0, lsb: 0, program: 105, name: "Sitar 1" },
    { msb: 0, lsb: 32, program: 105, name: "Detuned Sitar" },
    { msb: 0, lsb: 35, program: 105, name: "Sitar 2" },
    { msb: 0, lsb: 0, program: 112, name: "Shehnai" },
    { msb: 0, lsb: 97, program: 106, name: "Gopichant" },
    { msb: 0, lsb: 116, program: 117, name: "Tabla" },
    { msb: 0, lsb: 115, program: 111, name: "Er Hu" },
    { msb: 0, lsb: 118, program: 74, name: "Di Zi" },
    { msb: 0, lsb: 116, program: 106, name: "Pi Pa" },
    { msb: 0, lsb: 113, program: 108, name: "Gu Zheng" },
    { msb: 0, lsb: 40, program: 47, name: "Yang Qin" },
    { msb: 0, lsb: 120, program: 111, name: "Morin Khuur" },
    { msb: 0, lsb: 124, program: 74, name: "Suling" },
    { msb: 0, lsb: 0, program: 107, name: "Shamisen" },
    { msb: 0, lsb: 0, program: 108, name: "Koto" },
    { msb: 0, lsb: 96, program: 108, name: "Taisho-kin" },
  ],
  'DUAL*': [
  ],
  'SOUND EFFECT': [
    { msb: 0, lsb: 0, program: 121, name: "Fret Noise" },
    { msb: 0, lsb: 0, program: 122, name: "Breath Noise" },
    { msb: 0, lsb: 0, program: 123, name: "Seashore" },
    { msb: 0, lsb: 0, program: 124, name: "Bird Tweet" },
    { msb: 0, lsb: 0, program: 125, name: "Telephone Ring" },
    { msb: 0, lsb: 0, program: 126, name: "Helicopter" },
    { msb: 0, lsb: 0, program: 127, name: "Applause" },
    { msb: 0, lsb: 113, program: 116, name: "Hand Clap" },
    { msb: 0, lsb: 0, program: 128, name: "Gunshot" },
  ],
  'DRUM KIT': [
    { msb: 127, lsb: 0, program: 88, name: "Power Kit" },
    { msb: 127, lsb: 0, program: 1, name: "Standard Kit 1" },
    { msb: 127, lsb: 0, program: 2, name: "Standard Kit 2" },
    { msb: 127, lsb: 0, program: 9, name: "Room Kit" },
    { msb: 127, lsb: 0, program: 17, name: "Rock Kit" },
    { msb: 127, lsb: 0, program: 25, name: "Electronic Kit" },
    { msb: 127, lsb: 0, program: 26, name: "Analog Kit" },
    { msb: 127, lsb: 0, program: 113, name: "Dance Kit" },
    { msb: 127, lsb: 0, program: 33, name: "Jazz Kit" },
    { msb: 127, lsb: 0, program: 41, name: "Brush Kit" },
    { msb: 127, lsb: 0, program: 49, name: "Symphony Kit" },
    { msb: 126, lsb: 0, program: 128, name: "StdKit 1 plus Chinese Perc." },
    { msb: 126, lsb: 0, program: 40, name: "Indian Kit 1" },
    { msb: 126, lsb: 0, program: 115, name: "Indian Kit 2" },
    { msb: 126, lsb: 0, program: 55, name: "StdKit 1 plus Indonesian Perc. 1" },
    { msb: 126, lsb: 0, program: 56, name: "StdKit 1 plus Indonesian Perc. 2" },
    { msb: 126, lsb: 0, program: 57, name: "StdKit 1 plus Indonesian Perc. 3" },
    { msb: 126, lsb: 0, program: 37, name: "Arabic Kit" },
    { msb: 126, lsb: 0, program: 41, name: "Cuban Kit" },
    { msb: 126, lsb: 0, program: 1, name: "SFX Kit 1" },
    { msb: 126, lsb: 0, program: 2, name: "SFX Kit 2" },
    { msb: 126, lsb: 0, program: 113, name: "Sound Effect Kit" },
  ],
  'ARPEGGIO**': [
  ],
  'XGlite Voice List': [
  ],
  'XG PIANO': [
    { msb: 0, lsb: 0, program: 1, name: "Grand Piano" },
    { msb: 0, lsb: 1, program: 1, name: "Grand Piano KSP" },
    { msb: 0, lsb: 40, program: 1, name: "Piano Strings" },
    { msb: 0, lsb: 41, program: 1, name: "Dream" },
    { msb: 0, lsb: 0, program: 2, name: "Bright Piano" },
    { msb: 0, lsb: 1, program: 2, name: "Bright Piano KSP" },
    { msb: 0, lsb: 0, program: 3, name: "Electric Grand Piano" },
    { msb: 0, lsb: 1, program: 3, name: "Electric Grand Piano KSP" },
    { msb: 0, lsb: 32, program: 3, name: "Detuned CP80" },
    { msb: 0, lsb: 0, program: 4, name: "Honky Tonk Piano" },
    { msb: 0, lsb: 1, program: 4, name: "Honky Tonk Piano KSP" },
    { msb: 0, lsb: 0, program: 5, name: "Electric Piano 1" },
    { msb: 0, lsb: 1, program: 5, name: "Electric Piano 1 KSP" },
    { msb: 0, lsb: 32, program: 5, name: "Chorus Electric Piano 1" },
    { msb: 0, lsb: 0, program: 6, name: "Electric Piano 2" },
    { msb: 0, lsb: 1, program: 6, name: "Electric Piano 2 KSP" },
    { msb: 0, lsb: 32, program: 6, name: "Chorus Electric Piano 2" },
    { msb: 0, lsb: 41, program: 6, name: "DX plus Analog Electric Piano" },
    { msb: 0, lsb: 0, program: 7, name: "Harpsichord 1" },
    { msb: 0, lsb: 1, program: 7, name: "Harpsichord KSP" },
    { msb: 0, lsb: 35, program: 7, name: "Harpsichord 2" },
    { msb: 0, lsb: 0, program: 8, name: "Clavi" },
    { msb: 0, lsb: 1, program: 8, name: "Clavi KSP" },
  ],
  'XG CHROMATIC': [
    { msb: 0, lsb: 0, program: 9, name: "Celesta" },
    { msb: 0, lsb: 0, program: 10, name: "Glockenspiel" },
    { msb: 0, lsb: 0, program: 11, name: "Music Box 1" },
    { msb: 0, lsb: 64, program: 11, name: "Music Box 2" },
    { msb: 0, lsb: 0, program: 12, name: "Vibraphone" },
    { msb: 0, lsb: 1, program: 12, name: "Vibraphone KSP" },
    { msb: 0, lsb: 0, program: 13, name: "Marimba" },
    { msb: 0, lsb: 1, program: 13, name: "Marimba KSP" },
    { msb: 0, lsb: 64, program: 13, name: "Sine Marimba" },
    { msb: 0, lsb: 97, program: 13, name: "Balimba" },
    { msb: 0, lsb: 98, program: 13, name: "Log Drums" },
    { msb: 0, lsb: 0, program: 14, name: "Xylophone" },
    { msb: 0, lsb: 0, program: 15, name: "Tubular Bells" },
    { msb: 0, lsb: 96, program: 15, name: "Church Bells" },
    { msb: 0, lsb: 97, program: 15, name: "Carillon" },
  ],
  'XG ORGAN': [
    { msb: 0, lsb: 0, program: 17, name: "Drawbar Organ 1" },
    { msb: 0, lsb: 32, program: 17, name: "Detuned Drawbar Organ" },
    { msb: 0, lsb: 33, program: 17, name: "60s Drawbar Organ 1" },
    { msb: 0, lsb: 34, program: 17, name: "60s Drawbar Organ 2" },
    { msb: 0, lsb: 35, program: 17, name: "70s Drawbar Organ 1" },
    { msb: 0, lsb: 37, program: 17, name: "60s Drawbar Organ 3" },
    { msb: 0, lsb: 40, program: 17, name: "16 plus 2'2/3 Organ" },
    { msb: 0, lsb: 64, program: 17, name: "Organ Bass" },
    { msb: 0, lsb: 65, program: 17, name: "70s Drawbar Organ 2" },
    { msb: 0, lsb: 66, program: 17, name: "Cheezy Organ" },
    { msb: 0, lsb: 67, program: 17, name: "Drawbar Organ 2" },
    { msb: 0, lsb: 0, program: 18, name: "Percussive Organ 1" },
    { msb: 0, lsb: 24, program: 18, name: "70s Percussive Organ" },
    { msb: 0, lsb: 32, program: 18, name: "Detuned Percussive Organ" },
    { msb: 0, lsb: 33, program: 18, name: "Light Organ" },
    { msb: 0, lsb: 37, program: 18, name: "Percussive Organ 2" },
    { msb: 0, lsb: 0, program: 19, name: "Rock Organ" },
    { msb: 0, lsb: 64, program: 19, name: "Rotary Organ" },
    { msb: 0, lsb: 65, program: 19, name: "Slow Rotary Organ" },
    { msb: 0, lsb: 66, program: 19, name: "Fast Rotary Organ" },
    { msb: 0, lsb: 0, program: 20, name: "Church Organ 1" },
    { msb: 0, lsb: 32, program: 20, name: "Church Organ 3" },
    { msb: 0, lsb: 35, program: 20, name: "Church Organ 2" },
    { msb: 0, lsb: 40, program: 20, name: "Notre Dame" },
    { msb: 0, lsb: 64, program: 20, name: "Organ Flute" },
    { msb: 0, lsb: 65, program: 20, name: "Tremolo Organ Flute" },
    { msb: 0, lsb: 0, program: 21, name: "Reed Organ" },
    { msb: 0, lsb: 40, program: 21, name: "Puff Organ" },
    { msb: 0, lsb: 0, program: 22, name: "Accordion" },
    { msb: 0, lsb: 0, program: 23, name: "Harmonica 1" },
    { msb: 0, lsb: 32, program: 23, name: "Harmonica 2" },
    { msb: 0, lsb: 0, program: 24, name: "Tango Accordion 1" },
    { msb: 0, lsb: 64, program: 24, name: "Tango Accordion 2" },
  ],
  'XG GUITAR': [
    { msb: 0, lsb: 0, program: 25, name: "Nylon Guitar 1" },
    { msb: 0, lsb: 25, program: 25, name: "Nylon Guitar 3" },
    { msb: 0, lsb: 43, program: 25, name: "Velocity Guitar Harmonics" },
    { msb: 0, lsb: 96, program: 25, name: "Ukulele" },
    { msb: 0, lsb: 0, program: 26, name: "Steel Guitar" },
    { msb: 0, lsb: 35, program: 26, name: "12-string Guitar" },
    { msb: 0, lsb: 40, program: 26, name: "Nylon and Steel Guitar" },
    { msb: 0, lsb: 41, program: 26, name: "Steel Guitar with Body Sound" },
    { msb: 0, lsb: 96, program: 26, name: "Mandolin" },
    { msb: 0, lsb: 0, program: 27, name: "Jazz Guitar" },
    { msb: 0, lsb: 32, program: 27, name: "Jazz Amp" },
    { msb: 0, lsb: 0, program: 28, name: "Clean Guitar" },
    { msb: 0, lsb: 32, program: 28, name: "Chorus Guitar" },
    { msb: 0, lsb: 0, program: 29, name: "Muted Guitar" },
    { msb: 0, lsb: 40, program: 29, name: "Funk Guitar" },
    { msb: 0, lsb: 41, program: 29, name: "Muted Steel Guitar" },
    { msb: 0, lsb: 45, program: 29, name: "Jazz Man" },
    { msb: 0, lsb: 0, program: 30, name: "Overdriven Guitar" },
    { msb: 0, lsb: 43, program: 30, name: "Guitar Pinch" },
    { msb: 0, lsb: 0, program: 31, name: "Distortion Guitar" },
    { msb: 0, lsb: 40, program: 31, name: "Feedback Guitar 1" },
    { msb: 0, lsb: 41, program: 31, name: "Feedback Guitar 2" },
    { msb: 0, lsb: 0, program: 32, name: "Guitar Harmonics 1" },
    { msb: 0, lsb: 65, program: 32, name: "Guitar Feedback" },
    { msb: 0, lsb: 66, program: 32, name: "Guitar Harmonics 2" },
  ],
  'XG BASS': [
    { msb: 0, lsb: 0, program: 33, name: "Acoustic Bass" },
    { msb: 0, lsb: 40, program: 33, name: "Jazz Rhythm" },
    { msb: 0, lsb: 45, program: 33, name: "Velocity Crossfade Upright Bass" },
    { msb: 0, lsb: 0, program: 34, name: "Finger Bass 1" },
    { msb: 0, lsb: 18, program: 34, name: "Finger Bass Dark" },
    { msb: 0, lsb: 40, program: 34, name: "Bass and Distorted Electric Guitar" },
    { msb: 0, lsb: 43, program: 34, name: "Finger Slap Bass" },
    { msb: 0, lsb: 45, program: 34, name: "Finger Bass 2" },
    { msb: 0, lsb: 65, program: 34, name: "Modulated Bass" },
    { msb: 0, lsb: 0, program: 35, name: "Pick Bass" },
    { msb: 0, lsb: 28, program: 35, name: "Muted Pick Bass" },
    { msb: 0, lsb: 0, program: 36, name: "Fretless Bass 1" },
    { msb: 0, lsb: 32, program: 36, name: "Fretless Bass 2" },
    { msb: 0, lsb: 33, program: 36, name: "Fretless Bass 3" },
    { msb: 0, lsb: 34, program: 36, name: "Fretless Bass 4" },
    { msb: 0, lsb: 0, program: 37, name: "Slap Bass 1" },
    { msb: 0, lsb: 32, program: 37, name: "Punch Thumb Bass" },
    { msb: 0, lsb: 0, program: 38, name: "Slap Bass 2" },
    { msb: 0, lsb: 43, program: 38, name: "Velocity Switch Slap" },
    { msb: 0, lsb: 0, program: 39, name: "Synth Bass 1" },
    { msb: 0, lsb: 40, program: 39, name: "Techno Synth Bass" },
    { msb: 0, lsb: 0, program: 40, name: "Synth Bass 2" },
    { msb: 0, lsb: 6, program: 40, name: "Mellow Synth Bass" },
    { msb: 0, lsb: 12, program: 40, name: "Sequenced Bass" },
    { msb: 0, lsb: 18, program: 40, name: "Click Synth Bass" },
    { msb: 0, lsb: 19, program: 40, name: "Synth Bass 2 Dark" },
    { msb: 0, lsb: 40, program: 40, name: "Modular Synth Bass" },
    { msb: 0, lsb: 41, program: 40, name: "DX Bass" },
  ],
  'XG STRINGS': [
    { msb: 0, lsb: 0, program: 41, name: "Violin" },
    { msb: 0, lsb: 8, program: 41, name: "Slow Violin" },
    { msb: 0, lsb: 0, program: 42, name: "Viola" },
    { msb: 0, lsb: 0, program: 43, name: "Cello" },
    { msb: 0, lsb: 0, program: 44, name: "Contrabass" },
    { msb: 0, lsb: 0, program: 45, name: "Tremolo Strings" },
    { msb: 0, lsb: 8, program: 45, name: "Slow Tremolo Strings" },
    { msb: 0, lsb: 40, program: 45, name: "Suspense Strings" },
    { msb: 0, lsb: 0, program: 46, name: "Pizzicato Strings" },
    { msb: 0, lsb: 0, program: 47, name: "Orchestral Harp" },
    { msb: 0, lsb: 0, program: 48, name: "Timpani" },
  ],
  'XG ENSEMBLE': [
    { msb: 0, lsb: 0, program: 49, name: "Strings 1" },
    { msb: 0, lsb: 3, program: 49, name: "Stereo Strings" },
    { msb: 0, lsb: 8, program: 49, name: "Slow Strings" },
    { msb: 0, lsb: 35, program: 49, name: "60s Strings" },
    { msb: 0, lsb: 40, program: 49, name: "Orchestra 1" },
    { msb: 0, lsb: 41, program: 49, name: "Orchestra 2" },
    { msb: 0, lsb: 42, program: 49, name: "Tremolo Orchestra" },
    { msb: 0, lsb: 45, program: 49, name: "Velocity Strings" },
    { msb: 0, lsb: 0, program: 50, name: "Strings 2" },
    { msb: 0, lsb: 3, program: 50, name: "Stereo Slow Strings" },
    { msb: 0, lsb: 8, program: 50, name: "Legato Strings" },
    { msb: 0, lsb: 40, program: 50, name: "Warm Strings" },
    { msb: 0, lsb: 41, program: 50, name: "Kingdom" },
    { msb: 0, lsb: 0, program: 51, name: "Synth Strings 1" },
    { msb: 0, lsb: 64, program: 51, name: "Synth Strings 4" },
    { msb: 0, lsb: 0, program: 52, name: "Synth Strings 2" },
    { msb: 0, lsb: 0, program: 53, name: "Choir Aahs" },
    { msb: 0, lsb: 3, program: 53, name: "Stereo Choir" },
    { msb: 0, lsb: 32, program: 53, name: "Mellow Choir" },
    { msb: 0, lsb: 40, program: 53, name: "Choir Strings" },
    { msb: 0, lsb: 0, program: 54, name: "Voice Oohs" },
    { msb: 0, lsb: 0, program: 55, name: "Synth Voice 1" },
    { msb: 0, lsb: 40, program: 55, name: "Synth Voice 2" },
    { msb: 0, lsb: 41, program: 55, name: "Choral" },
    { msb: 0, lsb: 64, program: 55, name: "Analog Voice" },
    { msb: 0, lsb: 0, program: 56, name: "Orchestra Hit 1" },
    { msb: 0, lsb: 35, program: 56, name: "Orchestra Hit 2" },
    { msb: 0, lsb: 64, program: 56, name: "Impact" },
  ],
  'XG BRASS': [
    { msb: 0, lsb: 0, program: 57, name: "Trumpet" },
    { msb: 0, lsb: 32, program: 57, name: "Warm Trumpet" },
    { msb: 0, lsb: 0, program: 58, name: "Trombone 1" },
    { msb: 0, lsb: 18, program: 58, name: "Trombone 2" },
    { msb: 0, lsb: 0, program: 59, name: "Tuba" },
    { msb: 0, lsb: 0, program: 60, name: "Muted Trumpet" },
    { msb: 0, lsb: 0, program: 61, name: "French Horn 1" },
    { msb: 0, lsb: 6, program: 61, name: "French Horn Solo" },
    { msb: 0, lsb: 32, program: 61, name: "French Horn 2" },
    { msb: 0, lsb: 37, program: 61, name: "Horn Orchestra" },
    { msb: 0, lsb: 0, program: 62, name: "Brass Section" },
    { msb: 0, lsb: 35, program: 62, name: "Trumpet and Trombone Section" },
    { msb: 0, lsb: 0, program: 63, name: "Synth Brass 1" },
    { msb: 0, lsb: 20, program: 63, name: "Resonant Synth Brass" },
    { msb: 0, lsb: 0, program: 64, name: "Synth Brass 2" },
    { msb: 0, lsb: 18, program: 64, name: "Soft Brass" },
    { msb: 0, lsb: 41, program: 64, name: "Choir Brass" },
  ],
  'XG REED': [
    { msb: 0, lsb: 0, program: 65, name: "Soprano Sax" },
    { msb: 0, lsb: 0, program: 66, name: "Alto Sax" },
    { msb: 0, lsb: 40, program: 66, name: "Sax Section" },
    { msb: 0, lsb: 0, program: 67, name: "Tenor Sax" },
    { msb: 0, lsb: 40, program: 67, name: "Breathy Tenor Sax" },
    { msb: 0, lsb: 0, program: 68, name: "Baritone Sax" },
    { msb: 0, lsb: 0, program: 69, name: "Oboe" },
    { msb: 0, lsb: 0, program: 70, name: "English Horn" },
    { msb: 0, lsb: 0, program: 71, name: "Bassoon" },
    { msb: 0, lsb: 0, program: 72, name: "Clarinet" },
  ],
  'XG PIPE': [
    { msb: 0, lsb: 0, program: 73, name: "Piccolo" },
    { msb: 0, lsb: 0, program: 74, name: "Flute" },
    { msb: 0, lsb: 0, program: 75, name: "Recorder" },
    { msb: 0, lsb: 0, program: 76, name: "Pan Flute" },
    { msb: 0, lsb: 0, program: 77, name: "Blown Bottle" },
    { msb: 0, lsb: 0, program: 79, name: "Whistle" },
    { msb: 0, lsb: 0, program: 80, name: "Ocarina" },
  ],
  'XG SYNTH LEAD': [
    { msb: 0, lsb: 0, program: 81, name: "Square Lead 1" },
    { msb: 0, lsb: 6, program: 81, name: "Square Lead 2" },
    { msb: 0, lsb: 8, program: 81, name: "LM Square" },
    { msb: 0, lsb: 18, program: 81, name: "Hollow" },
    { msb: 0, lsb: 19, program: 81, name: "Shroud" },
    { msb: 0, lsb: 64, program: 81, name: "Mellow" },
    { msb: 0, lsb: 65, program: 81, name: "Solo Sine" },
    { msb: 0, lsb: 66, program: 81, name: "Sine Lead" },
    { msb: 0, lsb: 0, program: 82, name: "Sawtooth Lead 1" },
    { msb: 0, lsb: 6, program: 82, name: "Sawtooth Lead 2" },
    { msb: 0, lsb: 8, program: 82, name: "Thick Sawtooth" },
    { msb: 0, lsb: 18, program: 82, name: "Dynamic Sawtooth" },
    { msb: 0, lsb: 19, program: 82, name: "Digital Sawtooth" },
    { msb: 0, lsb: 20, program: 82, name: "Big Lead" },
    { msb: 0, lsb: 24, program: 82, name: "Heavy Synth" },
    { msb: 0, lsb: 96, program: 82, name: "Sequenced Analog" },
    { msb: 0, lsb: 0, program: 83, name: "Calliope Lead" },
    { msb: 0, lsb: 65, program: 83, name: "Pure Lead" },
    { msb: 0, lsb: 0, program: 84, name: "Chiff Lead" },
    { msb: 0, lsb: 0, program: 85, name: "Charang Lead" },
    { msb: 0, lsb: 64, program: 85, name: "Distorted Lead" },
    { msb: 0, lsb: 0, program: 86, name: "Voice Lead" },
    { msb: 0, lsb: 0, program: 87, name: "Fifths Lead" },
    { msb: 0, lsb: 35, program: 87, name: "Big Five" },
    { msb: 0, lsb: 0, program: 88, name: "Bass and Lead" },
    { msb: 0, lsb: 16, program: 88, name: "Big and Low" },
    { msb: 0, lsb: 64, program: 88, name: "Fat and Perky" },
    { msb: 0, lsb: 65, program: 88, name: "Soft Whirl" },
  ],
  'XG SYNTH PAD': [
    { msb: 0, lsb: 0, program: 89, name: "New Age Pad" },
    { msb: 0, lsb: 64, program: 89, name: "Fantasy" },
    { msb: 0, lsb: 0, program: 90, name: "Warm Pad" },
    { msb: 0, lsb: 0, program: 91, name: "Poly Synth Pad" },
    { msb: 0, lsb: 0, program: 92, name: "Choir Pad" },
    { msb: 0, lsb: 66, program: 92, name: "Itopia" },
    { msb: 0, lsb: 0, program: 93, name: "Bowed Pad" },
    { msb: 0, lsb: 0, program: 94, name: "Metallic Pad" },
    { msb: 0, lsb: 0, program: 95, name: "Halo Pad" },
    { msb: 0, lsb: 0, program: 96, name: "Sweep Pad" },
  ],
  'XG SYNTH EFFECTS': [
    { msb: 0, lsb: 0, program: 97, name: "Rain" },
    { msb: 0, lsb: 64, program: 97, name: "Harmo Rain" },
    { msb: 0, lsb: 65, program: 97, name: "African Wind" },
    { msb: 0, lsb: 66, program: 97, name: "Carib" },
    { msb: 0, lsb: 0, program: 98, name: "Sound Track" },
    { msb: 0, lsb: 27, program: 98, name: "Prologue" },
    { msb: 0, lsb: 0, program: 99, name: "Crystal" },
    { msb: 0, lsb: 12, program: 99, name: "Synth Drum Comp" },
    { msb: 0, lsb: 14, program: 99, name: "Popcorn" },
    { msb: 0, lsb: 18, program: 99, name: "Tiny Bells" },
    { msb: 0, lsb: 35, program: 99, name: "Round Glockenspiel" },
    { msb: 0, lsb: 40, program: 99, name: "Glockenspiel Chimes" },
    { msb: 0, lsb: 41, program: 99, name: "Clear Bells" },
    { msb: 0, lsb: 42, program: 99, name: "Chorus Bells" },
    { msb: 0, lsb: 65, program: 99, name: "Soft Crystal" },
    { msb: 0, lsb: 70, program: 99, name: "Air Bells" },
    { msb: 0, lsb: 71, program: 99, name: "Bell Harp" },
    { msb: 0, lsb: 72, program: 99, name: "Gamelimba" },
    { msb: 0, lsb: 0, program: 100, name: "Atmosphere" },
    { msb: 0, lsb: 18, program: 100, name: "Warm Atmosphere" },
    { msb: 0, lsb: 19, program: 100, name: "Hollow Release" },
    { msb: 0, lsb: 40, program: 100, name: "Nylon Electric Piano" },
    { msb: 0, lsb: 64, program: 100, name: "Nylon Harp" },
    { msb: 0, lsb: 65, program: 100, name: "Harp Vox" },
    { msb: 0, lsb: 66, program: 100, name: "Atmosphere Pad" },
    { msb: 0, lsb: 0, program: 101, name: "Brightness" },
    { msb: 0, lsb: 0, program: 102, name: "Goblins" },
    { msb: 0, lsb: 64, program: 102, name: "Goblins Synth" },
    { msb: 0, lsb: 65, program: 102, name: "Creeper" },
    { msb: 0, lsb: 67, program: 102, name: "Ritual" },
    { msb: 0, lsb: 68, program: 102, name: "To Heaven" },
    { msb: 0, lsb: 70, program: 102, name: "Night" },
    { msb: 0, lsb: 71, program: 102, name: "Glisten" },
    { msb: 0, lsb: 96, program: 102, name: "Bell Choir" },
    { msb: 0, lsb: 0, program: 103, name: "Echoes" },
    { msb: 0, lsb: 65, program: 103, name: "Big Pan" },
    { msb: 0, lsb: 0, program: 104, name: "Sci-Fi" },
  ],
  'XG WORLD': [
    { msb: 0, lsb: 0, program: 78, name: "Shakuhachi" },
    { msb: 0, lsb: 97, program: 105, name: "Tamboura" },
    { msb: 0, lsb: 0, program: 106, name: "Banjo" },
    { msb: 0, lsb: 28, program: 106, name: "Muted Banjo" },
  ],
  'XG PERCUSSIVE': [
    { msb: 0, lsb: 0, program: 113, name: "Tinkle Bell" },
    { msb: 0, lsb: 96, program: 113, name: "Bonang" },
    { msb: 0, lsb: 97, program: 113, name: "Altair" },
    { msb: 0, lsb: 98, program: 113, name: "Gamelan Gongs" },
    { msb: 0, lsb: 99, program: 113, name: "Stereo Gamelan Gongs" },
    { msb: 0, lsb: 100, program: 113, name: "Rama Cymbal" },
    { msb: 0, lsb: 0, program: 114, name: "Agogo" },
    { msb: 0, lsb: 0, program: 115, name: "Steel Drums" },
    { msb: 0, lsb: 97, program: 115, name: "Glass Percussion" },
    { msb: 0, lsb: 98, program: 115, name: "Thai Bells" },
    { msb: 0, lsb: 0, program: 116, name: "Woodblock" },
    { msb: 0, lsb: 96, program: 116, name: "Castanets" },
    { msb: 0, lsb: 0, program: 117, name: "Taiko Drum" },
    { msb: 0, lsb: 96, program: 117, name: "Gran Cassa" },
    { msb: 0, lsb: 0, program: 118, name: "Melodic Tom 1" },
    { msb: 0, lsb: 64, program: 118, name: "Melodic Tom 2" },
    { msb: 0, lsb: 65, program: 118, name: "Real Tom" },
    { msb: 0, lsb: 66, program: 118, name: "Rock Tom" },
    { msb: 0, lsb: 0, program: 119, name: "Synth Drum" },
    { msb: 0, lsb: 64, program: 119, name: "Analog Tom" },
    { msb: 0, lsb: 65, program: 119, name: "Electronic Percussion" },
    { msb: 0, lsb: 0, program: 120, name: "Reverse Cymbal" },
  ],
  'XG SOUND EFFECTS': [
    { msb: 64, lsb: 0, program: 1, name: "Cutting Noise 1" },
    { msb: 64, lsb: 0, program: 2, name: "Cutting Noise 2" },
    { msb: 64, lsb: 0, program: 4, name: "String Slap" },
    { msb: 64, lsb: 0, program: 17, name: "Flute Key Click" },
    { msb: 64, lsb: 0, program: 33, name: "Shower" },
    { msb: 64, lsb: 0, program: 34, name: "Thunder" },
    { msb: 64, lsb: 0, program: 35, name: "Wind" },
    { msb: 64, lsb: 0, program: 36, name: "Stream" },
    { msb: 64, lsb: 0, program: 37, name: "Bubble" },
    { msb: 64, lsb: 0, program: 38, name: "Feed" },
    { msb: 64, lsb: 0, program: 49, name: "Dog" },
    { msb: 64, lsb: 0, program: 50, name: "Horse" },
    { msb: 64, lsb: 0, program: 51, name: "Bird Tweet 2" },
    { msb: 64, lsb: 0, program: 56, name: "Maou" },
    { msb: 64, lsb: 0, program: 65, name: "Phone Call" },
    { msb: 64, lsb: 0, program: 66, name: "Door Squeak" },
    { msb: 64, lsb: 0, program: 67, name: "Door Slam" },
    { msb: 64, lsb: 0, program: 68, name: "Scratch Cut" },
    { msb: 64, lsb: 0, program: 69, name: "Scratch Split" },
    { msb: 64, lsb: 0, program: 70, name: "Wind Chime" },
    { msb: 64, lsb: 0, program: 71, name: "Telephone Ring 2" },
    { msb: 64, lsb: 0, program: 81, name: "Car Engine Ignition" },
    { msb: 64, lsb: 0, program: 82, name: "Car Tires Squeal" },
    { msb: 64, lsb: 0, program: 83, name: "Car Passing" },
    { msb: 64, lsb: 0, program: 84, name: "Car Crash" },
    { msb: 64, lsb: 0, program: 85, name: "Siren" },
    { msb: 64, lsb: 0, program: 86, name: "Train" },
    { msb: 64, lsb: 0, program: 87, name: "Jet Plane" },
    { msb: 64, lsb: 0, program: 88, name: "Starship" },
    { msb: 64, lsb: 0, program: 89, name: "Burst" },
    { msb: 64, lsb: 0, program: 90, name: "Roller Coaster" },
    { msb: 64, lsb: 0, program: 91, name: "Submarine" },
    { msb: 64, lsb: 0, program: 97, name: "Laugh" },
    { msb: 64, lsb: 0, program: 98, name: "Scream" },
    { msb: 64, lsb: 0, program: 99, name: "Punch" },
    { msb: 64, lsb: 0, program: 100, name: "Heartbeat" },
    { msb: 64, lsb: 0, program: 101, name: "Footsteps" },
    { msb: 64, lsb: 0, program: 113, name: "Machine Gun" },
    { msb: 64, lsb: 0, program: 114, name: "Laser Gun" },
    { msb: 64, lsb: 0, program: 115, name: "Explosion" },
    { msb: 64, lsb: 0, program: 116, name: "Firework" },
  ],
};

